"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from glob import glob
from setuptools import setup

APP = ['liveStat.py']
APP_NAME = 'SaadBigD'
# DATA_FILES = [('', [''])]

DATA_FILES = [
    ('', glob('*.gif'))
]
OPTIONS = {
    'iconfile': 'basketball2.ico'
}

# DATA_FILES = [
#     ('', ['basketball2.gif']),
# ]

setup(
    app=APP,
    name=APP_NAME,
    data_files=DATA_FILES,

    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
